---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-gps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-gps
  template:
    metadata:
      labels:
        app: classroom-gps
    spec:
      containers:
      - name: classroom-gps-container
        image: classroom-gps:latest
        imagePullPolicy: Never # Forces Minikube to use the local image you build
        ports:
        - containerPort: 3000
        env:
        # Dynamically inject the location details here!
        - name: CLASSROOM_NAME
          value: "IIIT Kottayam"
        - name: LATITUDE
          value: "10.0575"
        - name: LONGITUDE
          value: "76.5520"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: classroom-gps-service
spec:
  type: NodePort
  selector:
    app: classroom-gps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
